# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '302d51b5-a5a8-4bdc-9182-4acca4264969'
  imageRepository: 'speckle/speckle-frontend'
  containerRegistry: 'acrmulticonsultdev.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/packages/speckle-frontend/Dockerfile'
  buildIdTag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Dev
    displayName: Dev
    jobs:
      - deployment:
        environment: speckle-dev
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build a docker image
            inputs:
              command: build
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(buildIdTag)
                latest
          - task: Docker@2
            displayName: Push docker image to Azure Container Registry
            inputs:
              command: push
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(buildIdTag)
                latest