trigger:
- main

resources:
- repo: self

variables:
  azureContainerRegistry: acrmulticonsultdev.azurecr.io
  azureSubscriptionEndpoint: acr_dev

steps:
- task: DockerCompose@0
  displayName: Container registry login
  inputs:
    containerregistrytype: Azure Container Registry
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)